# Generated by Django 5.2.11 on 2026-02-20 11:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content_type', models.CharField(choices=[('youtube', 'YouTube Video'), ('pdf', 'PDF Document'), ('ppt', 'PowerPoint Presentation'), ('word', 'Word Document')], max_length=20)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='learning_content/')),
                ('transcript', models.TextField(blank=True)),
                ('key_concepts', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConceptMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_name', models.CharField(max_length=200)),
                ('total_questions', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('mastery_level', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('next_review_date', models.DateTimeField(blank=True, null=True)),
                ('review_interval_days', models.IntegerField(default=1)),
                ('last_practiced_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['mastery_level', 'concept_name'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('total_questions', models.IntegerField(default=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('score', models.FloatField(blank=True, null=True)),
                ('adaptive_score', models.FloatField(blank=True, null=True)),
                ('time_taken_seconds', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='adaptive_learning.content')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_time_seconds', models.IntegerField(default=0)),
                ('active_time_seconds', models.IntegerField(default=0)),
                ('tab_switches', models.IntegerField(default=0)),
                ('focus_lost_count', models.IntegerField(default=0)),
                ('events', models.JSONField(default=list)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adaptive_learning.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('options', models.JSONField()),
                ('correct_answer_index', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('explanation', models.TextField()),
                ('difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=1)),
                ('concept', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='adaptive_learning.assessment')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RevisionQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField()),
                ('priority', models.IntegerField(default=1)),
                ('times_reviewed', models.IntegerField(default=0)),
                ('times_correct', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adaptive_learning.conceptmastery')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adaptive_learning.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_for', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('recommended', 'Recommended Session (2hr + 20min break)'), ('standard', 'Standard Session (50min + 10min break)')], default='recommended', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('study_duration_seconds', models.IntegerField(default=0)),
                ('break_duration_seconds', models.IntegerField(default=0)),
                ('break_started_at', models.DateTimeField(blank=True, null=True)),
                ('break_ended_at', models.DateTimeField(blank=True, null=True)),
                ('break_used', models.BooleanField(default=False)),
                ('break_expired', models.BooleanField(default=False)),
                ('reminder_70_shown', models.BooleanField(default=False)),
                ('reminder_90_shown', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('camera_enabled', models.BooleanField(default=False)),
                ('camera_permission_requested', models.BooleanField(default=False)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='adaptive_learning.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement_score', models.FloatField(default=0.0)),
                ('study_speed', models.FloatField(default=0.0)),
                ('interaction_rate', models.FloatField(default=0.0)),
                ('total_tab_switches', models.IntegerField(default=0)),
                ('total_focus_losses', models.IntegerField(default=0)),
                ('average_focus_duration_seconds', models.FloatField(default=0.0)),
                ('total_active_time_seconds', models.IntegerField(default=0)),
                ('total_idle_time_seconds', models.IntegerField(default=0)),
                ('active_time_ratio', models.FloatField(default=0.0)),
                ('content_interactions', models.JSONField(blank=True, default=dict)),
                ('chat_queries_count', models.IntegerField(default=0)),
                ('whiteboard_snapshots_count', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='adaptive_learning.studysession')),
            ],
            options={
                'verbose_name_plural': 'Session Metrics',
            },
        ),
        migrations.CreateModel(
            name='GeneratedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('total_questions', models.IntegerField(default=10)),
                ('mcq_count', models.IntegerField(default=4)),
                ('short_answer_count', models.IntegerField(default=3)),
                ('problem_solving_count', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_limit_seconds', models.IntegerField(default=1800)),
                ('score', models.FloatField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('weak_concepts', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_tests', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_test', to='adaptive_learning.studysession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice Question'), ('short_answer', 'Short Answer'), ('problem_solving', 'Problem Solving')], max_length=20)),
                ('question_text', models.TextField()),
                ('options', models.JSONField(blank=True, null=True)),
                ('correct_answer_index', models.IntegerField(blank=True, null=True)),
                ('expected_answer', models.TextField(blank=True, null=True)),
                ('evaluation_criteria', models.TextField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True)),
                ('concept', models.CharField(max_length=200)),
                ('difficulty', models.IntegerField(default=1)),
                ('order', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=1)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='adaptive_learning.generatedtest')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_difficulty', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('mastery_level', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('sessions_completed', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_topics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AddField(
            model_name='content',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='adaptive_learning.topic'),
        ),
        migrations.AddField(
            model_name='conceptmastery',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adaptive_learning.topic'),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer_index', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('is_correct', models.BooleanField()),
                ('time_taken_seconds', models.IntegerField()),
                ('attempt_number', models.IntegerField(default=1)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='adaptive_learning.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['answered_at'],
            },
        ),
        migrations.CreateModel(
            name='WhiteboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='whiteboard_snapshots/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whiteboard_snapshots', to='adaptive_learning.studysession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProctoringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('tab_switch', 'Tab Switch'), ('copy_attempt', 'Copy Attempt'), ('paste_attempt', 'Paste Attempt'), ('screenshot_blocked', 'Screenshot Blocked'), ('screenshot_allowed', 'Screenshot Allowed (Whiteboard/Chat)'), ('camera_enabled', 'Camera Enabled'), ('camera_disabled', 'Camera Disabled'), ('focus_lost', 'Window Focus Lost'), ('focus_gained', 'Window Focus Gained')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_events', to='adaptive_learning.studysession')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['session', 'event_type'], name='adaptive_le_session_28446b_idx')],
            },
        ),
        migrations.CreateModel(
            name='TestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True)),
                ('selected_index', models.IntegerField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('time_taken_seconds', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_by_ml', models.BooleanField(default=False)),
                ('ml_confidence', models.FloatField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='adaptive_learning.testquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['submitted_at'],
                'unique_together': {('question', 'user')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='conceptmastery',
            unique_together={('user', 'topic', 'concept_name')},
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_difficulty', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('mastery_level', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('total_assessments', models.IntegerField(default=0)),
                ('average_accuracy', models.FloatField(default=0.0)),
                ('average_time_per_question', models.FloatField(default=0.0)),
                ('first_attempt_correct_rate', models.FloatField(default=0.0)),
                ('last_score', models.FloatField(blank=True, null=True)),
                ('score_trend', models.FloatField(default=0.0)),
                ('last_session_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adaptive_learning.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
