# Generated by Django 6.0.2 on 2026-02-20 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive_learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='test_available_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='workspace_name',
            field=models.CharField(default='My Study Session', max_length=200),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='session_type',
            field=models.CharField(choices=[('recommended', 'Recommended Session (2hr + 20min break)'), ('standard', 'Standard Session (50min + 10min break)'), ('custom', 'Custom Session')], default='recommended', max_length=20),
        ),
        migrations.CreateModel(
            name='BrowserExtensionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_switches', models.IntegerField(default=0)),
                ('blocked_attempts', models.IntegerField(default=0)),
                ('blocked_sites', models.JSONField(default=list)),
                ('events', models.JSONField(default=list)),
                ('extension_active', models.BooleanField(default=False)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_data', to='adaptive_learning.studysession')),
            ],
            options={
                'ordering': ['-last_heartbeat'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField()),
                ('total_questions', models.IntegerField()),
                ('correct_answers', models.IntegerField()),
                ('time_taken_seconds', models.IntegerField()),
                ('mcq_score', models.FloatField(default=0.0)),
                ('short_answer_score', models.FloatField(default=0.0)),
                ('problem_solving_score', models.FloatField(default=0.0)),
                ('weak_topics', models.JSONField(default=list)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='adaptive_learning.studysession')),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='adaptive_learning.generatedtest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='WeakPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('subtopic', models.CharField(blank=True, max_length=200)),
                ('incorrect_count', models.IntegerField(default=0)),
                ('total_attempts', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('first_identified', models.DateTimeField(auto_now_add=True)),
                ('last_attempted', models.DateTimeField(auto_now=True)),
                ('recommendations_generated', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weak_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['confidence_score', '-incorrect_count'],
                'unique_together': {('user', 'topic', 'subtopic')},
            },
        ),
        migrations.CreateModel(
            name='CourseRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('source', models.CharField(max_length=50)),
                ('url', models.URLField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('relevance_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('viewed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_recommendations', to=settings.AUTH_USER_MODEL)),
                ('weak_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='adaptive_learning.weakpoint')),
            ],
            options={
                'ordering': ['-relevance_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('sessions_created', models.IntegerField(default=0)),
                ('max_sessions_per_day', models.IntegerField(default=3)),
                ('tests_pending', models.IntegerField(default=0)),
                ('tests_completed', models.IntegerField(default=0)),
                ('can_create_session', models.BooleanField(default=True)),
                ('blocked_reason', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_limits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
