# Generated by Django 6.0.2 on 2026-02-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive_learning', '0002_studysession_test_available_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='source_language',
            field=models.CharField(blank=True, default='en', max_length=10),
        ),
    ]
