# Generated by Django 6.0.2 on 2026-02-20 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive_learning', '0003_add_source_language_to_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionlimit',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
