# Generated by Django 6.0.2 on 2026-02-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive_learning', '0004_fix_sessionlimit_date_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(db_index=True, max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('result_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(db_index=True, max_length=300)),
                ('source', models.CharField(choices=[('google', 'Google Article'), ('youtube', 'YouTube Playlist'), ('stackoverflow', 'Stack Overflow Q&A')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('votes', models.CharField(blank=True, max_length=20)),
                ('channel', models.CharField(blank=True, max_length=200)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['topic', 'source'], name='adaptive_le_topic_f19a77_idx')],
            },
        ),
    ]
