# Generated by Django 6.0.2 on 2026-02-21 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive_learning', '0005_scrapejob_scrapedcontent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_summary', models.JSONField(default=dict)),
                ('concept_breakdown', models.JSONField(default=list)),
                ('behavioral_analysis', models.JSONField(default=dict)),
                ('response_patterns', models.JSONField(default=dict)),
                ('recommendations', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('report_version', models.CharField(default='1.0', max_length=10)),
                ('test_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='adaptive_learning.testresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
