# Generated by Django 6.0.2 on 2026-02-22 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive_learning', '0006_testreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='adaptive_learning.studysession'),
        ),
    ]
