# Generated by Django 6.0.2 on 2026-02-22 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive_learning', '0007_assessment_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='parent_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_tests', to='adaptive_learning.assessment'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='test_number',
            field=models.IntegerField(choices=[(1, 'Test 1 - Initial'), (2, 'Test 2 - Adaptive Retry')], default=1),
        ),
    ]
